from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from rich.console import Console

from dros.bootstrap import run_bootstrap
from dros.plugins import create_default_registry
from dros.settings import DrosPaths, DrosSettings
from dros.update import UpdateValidationError, run_update


def _console(output: StringIO) -> Console:
    return Console(file=output, force_terminal=False, color_system=None, width=120)


def _settings(tmp_path: Path) -> DrosSettings:
    return DrosSettings(
        sysRoot=tmp_path / "sysroot",
        paths=DrosPaths(configs=tmp_path / "configs", run=tmp_path / "run"),
    )


def _collectd_conf(settings: DrosSettings) -> Path:
    return settings.sys_root / "etc/collectd/collectd.conf"


def _commands(result: object) -> list[list[str]]:
    return [action.command for action in result.actions if action.command is not None]


def test_bootstrap_installs_collectd_and_writes_default_config(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)

    result = run_bootstrap(
        settings,
        console=_console(StringIO()),
        installed_packages=create_default_registry().owned_packages()
        - {"collectd", "liboping0", "lm-sensors", "rrdtool"},
    )

    content = _collectd_conf(settings).read_text(encoding="utf-8")
    assert "# Generated by DROS. Manual changes will be overwritten." in content
    assert "# Resource: Collectd/system" in content
    assert "Interval 10" in content
    assert "LoadPlugin cpu" in content
    assert "LoadPlugin rrdtool" in content
    assert 'DataDir "/var/lib/collectd/rrd"' in content
    assert "LoadPlugin unixsock" in content
    assert 'SocketFile "/run/collectd-unixsock"' in content
    assert "LoadPlugin ping" not in content

    commands = _commands(result)
    assert any(
        "install" in command
        and {"collectd", "liboping0", "lm-sensors", "rrdtool"} <= set(command)
        for command in commands
    )
    assert ["systemctl", "restart", "collectd.service"] in commands
    assert ["systemctl", "enable", "collectd.service"] in commands


def test_update_collectd_writes_ping_targets_and_restarts(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "collectd.yaml").write_text(
        """
apiVersion: dros/v1alpha1
kind: Collectd
metadata:
  name: system
spec:
  interval: 5
  plugins:
    interface:
      ignore:
        - /^veth/
        - docker0
    ping:
      enabled: true
      hosts:
        - 1.1.1.1
        - vps-hk
    sensors:
      enabled: true
""".lstrip(),
        encoding="utf-8",
    )

    result = run_update(settings, target="collectd", console=_console(StringIO()))

    content = _collectd_conf(settings).read_text(encoding="utf-8")
    assert "Interval 5" in content
    assert 'Interface "/^veth/"' in content
    assert 'Interface "docker0"' in content
    assert "IgnoreSelected true" in content
    assert "LoadPlugin ping" in content
    assert 'Host "1.1.1.1"' in content
    assert 'Host "vps-hk"' in content
    assert "LoadPlugin sensors" in content
    assert ["systemctl", "restart", "collectd.service"] in _commands(result)


def test_update_collectd_disabled_writes_placeholder_and_disables_service(
    tmp_path: Path,
) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "collectd.yaml").write_text(
        """
kind: Collectd
metadata:
  name: system
spec:
  enabled: false
""".lstrip(),
        encoding="utf-8",
    )

    result = run_update(settings, target="collectd/system", console=_console(StringIO()))

    content = _collectd_conf(settings).read_text(encoding="utf-8")
    assert "# disabled" in content
    assert ["systemctl", "disable", "--now", "collectd.service"] in _commands(result)


def test_collectd_rejects_non_system_name(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "collectd.yaml").write_text(
        """
kind: Collectd
metadata:
  name: custom
spec: {}
""".lstrip(),
        encoding="utf-8",
    )

    with pytest.raises(UpdateValidationError, match="metadata.name must be system"):
        run_update(settings, target="collectd", console=_console(StringIO()))
