from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from rich.console import Console

from dros.bootstrap import run_bootstrap
from dros.plugins import create_default_registry
from dros.settings import DrosPaths, DrosSettings
from dros.update import UpdateValidationError, run_config_check, run_update


def _console(output: StringIO) -> Console:
    return Console(file=output, force_terminal=False, color_system=None, width=100)


def _settings(tmp_path: Path) -> DrosSettings:
    return DrosSettings(
        sysRoot=tmp_path / "sysroot",
        paths=DrosPaths(configs=tmp_path / "configs"),
    )


def _write_wgsd_config(settings: DrosSettings) -> None:
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "wgsd.yaml").write_text(
        """
apiVersion: dros/v1alpha1
kind: WgsdCoreDNS
metadata:
  name: system
spec:
  bind: 127.0.0.1
  listen: 5304
  interfaces:
    - name: wg-foo
      domain: foo.wg.natureself.site
    - name: wg-bar
      domain: bar.wg.natureself.site.
""".lstrip(),
        encoding="utf-8",
    )


def test_bootstrap_does_not_install_wgsd_coredns_binary_without_config(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)

    run_bootstrap(
        settings,
        console=_console(StringIO()),
        installed_packages=create_default_registry().owned_packages(),
    )

    assert not (settings.sys_root / "usr/local/bin/coredns").exists()
    assert not (settings.sys_root / "etc/dros/wgsd/Corefile").exists()
    assert not (settings.sys_root / "etc/systemd/system/dros-wgsd-coredns.service").exists()


def test_update_wgsd_coredns_skips_service_when_coredns_is_missing(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    _write_wgsd_config(settings)
    output = StringIO()

    result = run_update(settings, target="wgsd", console=_console(output))

    assert "warning: WgsdCoreDNS/system: /usr/local/bin/coredns is not installed" in output.getvalue()
    assert not (settings.sys_root / "usr/local/bin/coredns").exists()

    corefile = (settings.sys_root / "etc/dros/wgsd/Corefile").read_text(encoding="utf-8")
    assert corefile == """# Generated by DROS. Manual changes will be overwritten.
# Resource: WgsdCoreDNS/system

(common) {
    bind 127.0.0.1
    cache
}

.:5304 {
    import common
    wgsd foo.wg.natureself.site. wg-foo
    wgsd bar.wg.natureself.site. wg-bar
}
"""

    assert not (settings.sys_root / "etc/systemd/system/dros-wgsd-coredns.service").exists()
    assert not any(action.command == ["systemctl", "daemon-reload"] for action in result.actions)
    assert not any(
        action.command == ["systemctl", "restart", "dros-wgsd-coredns.service"]
        for action in result.actions
    )


def test_update_wgsd_coredns_writes_service_when_coredns_exists(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    _write_wgsd_config(settings)
    binary = settings.sys_root / "usr/local/bin/coredns"
    binary.parent.mkdir(parents=True)
    binary.write_bytes(b"\x7fELF coredns")

    result = run_update(settings, target="wgsd", console=_console(StringIO()))

    service = (settings.sys_root / "etc/systemd/system/dros-wgsd-coredns.service").read_text(
        encoding="utf-8"
    )
    assert "Description=DROS WGSD CoreDNS" in service
    assert "ExecStart=/usr/local/bin/coredns -conf /etc/dros/wgsd/Corefile" in service
    assert "Restart=on-failure" in service
    assert any(action.command == ["systemctl", "daemon-reload"] for action in result.actions)
    assert any(
        action.command == ["systemctl", "restart", "dros-wgsd-coredns.service"]
        for action in result.actions
    )
    assert any(
        action.command == ["systemctl", "enable", "dros-wgsd-coredns.service"]
        for action in result.actions
    )


def test_wgsd_coredns_config_check_rejects_empty_interfaces(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "wgsd.yaml").write_text(
        """
kind: WgsdCoreDNS
metadata:
  name: system
spec:
  interfaces: []
""".lstrip(),
        encoding="utf-8",
    )

    with pytest.raises(UpdateValidationError) as exc_info:
        run_config_check(settings, console=_console(StringIO()))

    assert "WgsdCoreDNS/system: spec.interfaces must contain at least one item" in "\n".join(
        exc_info.value.errors
    )
