from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from rich.console import Console

from dros.events import process_event
from dros.settings import DrosPaths, DrosSettings
from dros.update import UpdateValidationError, run_update


def _console(output: StringIO) -> Console:
    return Console(file=output, force_terminal=False, color_system=None, width=120)


def _settings(tmp_path: Path) -> DrosSettings:
    return DrosSettings(
        sysRoot=tmp_path / "sysroot",
        paths=DrosPaths(configs=tmp_path / "configs", run=tmp_path / "run"),
    )


def _commands(result: object) -> list[list[str]]:
    return [action.command for action in result.actions if action.command is not None]


def test_update_resolvconf_writes_system_resolver(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "resolver.yaml").write_text(
        """
apiVersion: dros/v1alpha1
kind: ResolvConf
metadata:
  name: system
spec:
  nameservers:
    - 10.0.0.1
    - 223.5.5.5
  search:
    - lan
    - corp.example.com
  options:
    - timeout:2
    - attempts:2
""".lstrip(),
        encoding="utf-8",
    )

    run_update(settings, target="resolvconf", console=_console(StringIO()))

    assert (settings.sys_root / "etc/resolv.conf").read_text(encoding="utf-8") == (
        "# Generated by DROS. Manual changes will be overwritten.\n"
        "# Resource: ResolvConf/system\n"
        "nameserver 10.0.0.1\n"
        "nameserver 223.5.5.5\n"
        "search lan corp.example.com\n"
        "options timeout:2 attempts:2\n"
    )


def test_update_resolvconf_requires_system_name_and_nameserver(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "resolver.yaml").write_text(
        """
kind: ResolvConf
metadata:
  name: office
spec:
  nameservers: []
""".lstrip(),
        encoding="utf-8",
    )

    with pytest.raises(UpdateValidationError) as exc_info:
        run_update(settings, target="resolvconf", console=_console(StringIO()))

    assert "ResolvConf/office: metadata.name must be system" in exc_info.value.errors
    assert "ResolvConf/office: spec.nameservers must contain at least one item" in (
        exc_info.value.errors
    )


def test_update_ipv6pd_writes_dhcp6c_radvd_service_hooks_and_nft(
    tmp_path: Path,
) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "ipv6.yaml").write_text(
        """
apiVersion: dros/v1alpha1
kind: Interface
metadata:
  name: br-lan
spec:
  type: bridge
  extraAddresses:
    - fd02::1/64
---
apiVersion: dros/v1alpha1
kind: IPv6PD
metadata:
  name: system
spec:
  uplink: pppoe-telecom
  prefixLengthHint: 60
  delegatedPrefixLength: 60
  requestAddress: true
  acceptRA: 2
  dnsServers:
    - fd02::1
  searchDomains:
    - lan
  downstream:
    - iface: br-lan
      subnetId: 2
      ulaPrefix: fd02::/64
      rdnss:
        - fd02::1
      dnssl:
        - lan
""".lstrip(),
        encoding="utf-8",
    )

    result = run_update(settings, target="ipv6pd/system", console=_console(StringIO()))

    assert (settings.sys_root / (settings.paths.run / "ipv6").relative_to("/")).is_dir()

    dhcp6c = (settings.sys_root / "etc/dros/ipv6/dhcp6c.conf").read_text(
        encoding="utf-8"
    )
    assert "interface pppoe-telecom {" in dhcp6c
    assert "  send ia-na 1;" in dhcp6c
    assert "  send ia-pd 1;" in dhcp6c
    assert "  prefix ::/60 infinity;" in dhcp6c
    assert "  prefix-interface br-lan {" in dhcp6c
    assert "    sla-id 2;" in dhcp6c
    assert "    sla-len 4;" in dhcp6c
    assert "    ifid 1;" in dhcp6c

    radvd = (settings.sys_root / "etc/radvd.conf").read_text(encoding="utf-8")
    assert "interface br-lan" in radvd
    assert "  prefix ::/64" in radvd
    assert "  prefix fd02::/64" in radvd
    assert "  RDNSS fd02::1" in radvd
    assert "  DNSSL lan" in radvd

    service = (
        settings.sys_root / "etc/systemd/system/dros-ipv6-pd.service"
    ).read_text(encoding="utf-8")
    assert "Description=DROS DHCPv6 Prefix Delegation client" in service
    assert "ExecStart=/usr/sbin/dhcp6c -f -c /etc/dros/ipv6/dhcp6c.conf pppoe-telecom" in service
    assert "ip link show dev \"$iface\"" in service

    ifup_hook = (settings.sys_root / "etc/network/if-up.d/dros-ipv6").read_text(
        encoding="utf-8"
    )
    assert 'gw hook ipv6-refresh "$IFACE" --verbose 0' in ifup_hook
    assert '" pppoe-telecom br-lan "' in ifup_hook

    nft = (settings.sys_root / "etc/dros/nftables.d/15-ipv6pd.nft").read_text(
        encoding="utf-8"
    )
    assert "add rule inet dros_filter input_pre" in nft
    assert 'iifname "pppoe-telecom"' in nft
    assert 'oifname "br-lan"' in nft

    commands = _commands(result)
    assert ["systemctl", "daemon-reload"] in commands
    assert ["systemctl", "restart", "dros-ipv6-pd.service"] in commands
    assert ["systemctl", "restart", "radvd.service"] in commands
    assert any(
        command[:3]
        == ["sh", "-c", 'if [ -f "$1" ] && [ -f "$2" ]; then nft -f "$1"; fi']
        for command in commands
    )


def test_update_ipv6pd_disabled_writes_placeholders_and_disables_services(
    tmp_path: Path,
) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "ipv6.yaml").write_text(
        """
kind: IPv6PD
metadata:
  name: system
spec:
  enabled: false
""".lstrip(),
        encoding="utf-8",
    )

    result = run_update(settings, target="ipv6pd/system", console=_console(StringIO()))

    assert "# IPv6PD/system is disabled" in (
        settings.sys_root / "etc/dros/ipv6/dhcp6c.conf"
    ).read_text(encoding="utf-8")
    assert "# IPv6PD/system is disabled" in (
        settings.sys_root / "etc/radvd.conf"
    ).read_text(encoding="utf-8")
    assert "# IPv6PD/system is disabled" in (
        settings.sys_root / "etc/dros/nftables.d/15-ipv6pd.nft"
    ).read_text(encoding="utf-8")
    assert ["systemctl", "disable", "--now", "dros-ipv6-pd.service"] in _commands(result)
    assert ["systemctl", "disable", "--now", "radvd.service"] in _commands(result)


def test_ipv6pd_validation_collects_all_errors(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "ipv6.yaml").write_text(
        """
kind: IPv6PD
metadata:
  name: custom
spec:
  uplink: pppoe-wan
  prefixLengthHint: 65
  delegatedPrefixLength: 60
  acceptRA: 9
  downstream:
    - iface: br-lan
      subnetId: 16
      ulaPrefix: fd02::/63
""".lstrip(),
        encoding="utf-8",
    )

    with pytest.raises(UpdateValidationError) as exc_info:
        run_update(settings, target="ipv6pd", console=_console(StringIO()))

    assert "IPv6PD/custom: metadata.name must be system" in exc_info.value.errors
    assert "IPv6PD/custom: spec.prefixLengthHint must be between 1 and 64" in (
        exc_info.value.errors
    )
    assert "IPv6PD/custom: spec.acceptRA must be 0, 1, 2, or null" in (
        exc_info.value.errors
    )
    assert (
        "IPv6PD/custom: spec.downstream[0].subnetId must be between 0 and 15 "
        "for delegated prefix length 60"
    ) in exc_info.value.errors
    assert "IPv6PD/custom: spec.downstream[0].ulaPrefix must be an IPv6 /64 prefix" in (
        exc_info.value.errors
    )


def test_ipv6pd_event_refreshes_matching_interface(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.paths.configs.mkdir(parents=True)
    (settings.paths.configs / "ipv6.yaml").write_text(
        """
kind: IPv6PD
metadata:
  name: system
spec:
  uplink: pppoe-telecom
  downstream:
    - iface: br-lan
      subnetId: 2
""".lstrip(),
        encoding="utf-8",
    )

    result = process_event(
        settings,
        "ppp-up",
        iface="pppoe-telecom",
        console=_console(StringIO()),
    )

    assert ["systemctl", "restart", "dros-ipv6-pd.service"] in _commands(result)
    assert ["systemctl", "restart", "radvd.service"] in _commands(result)
