from __future__ import annotations

import shlex
import re

from pydantic import ValidationError

from dros.config_objects import ConfigMapConfig, ConfigObject, CronJobConfig
from dros.plugins.base import DrosPlugin, UpdateContext

CRON_D_DIR = "/etc/cron.d"


def create_plugin() -> DrosPlugin:
    return DrosPlugin(
        name="config.resources",
        config_kinds=frozenset({"ConfigMap", "CronJob"}),
        managed_files=frozenset({"/etc/cron.d/dros-*"}),
        validation_hook=validate,
        update_hook=update,
    )


def validate(context: UpdateContext, objects: list[ConfigObject]) -> list[str]:
    errors: list[str] = []
    for obj in objects:
        if obj.kind == "ConfigMap":
            config = _validate_model(context, obj, ConfigMapConfig, errors)
            if config is not None:
                _validate_configmap(obj, config, errors)
        elif obj.kind == "CronJob":
            config = _validate_model(context, obj, CronJobConfig, errors)
            if config is not None:
                _validate_cronjob(obj, config, errors)
    return errors


def update(context: UpdateContext, objects: list[ConfigObject]) -> None:
    for obj in sorted(objects, key=lambda item: (item.kind, item.name)):
        if obj.kind != "CronJob":
            continue
        config = context.configs.resolve_object(obj, CronJobConfig)
        context.executor.write_file(_cron_path(obj.name), _render_cronjob(obj, config))


def _validate_model(
    context: UpdateContext,
    obj: ConfigObject,
    model_type: type[ConfigMapConfig] | type[CronJobConfig],
    errors: list[str],
) -> ConfigMapConfig | CronJobConfig | None:
    try:
        return context.configs.resolve_object(obj, model_type)
    except ValidationError as exc:
        for error in exc.errors():
            location = ".".join(str(part) for part in error["loc"])
            errors.append(f"{obj.kind}/{obj.name}: spec.{location}: {error['msg']}")
        return None


def _validate_configmap(
    obj: ConfigObject,
    config: ConfigMapConfig,
    errors: list[str],
) -> None:
    if not config.files:
        errors.append(f"ConfigMap/{obj.name}: spec.files must not be empty")
    for key in config.files:
        if key.startswith("/") or ".." in key.split("/"):
            errors.append(
                f"ConfigMap/{obj.name}: spec.files.{key}: key must be a relative file path"
            )


def _validate_cronjob(
    obj: ConfigObject,
    config: CronJobConfig,
    errors: list[str],
) -> None:
    if len(config.schedule.split()) != 5:
        errors.append(f"CronJob/{obj.name}: spec.schedule must be a 5-field cron schedule")
    for field_name, value in (
        ("schedule", config.schedule),
        ("user", config.user),
        ("command", config.command),
        ("comment", config.comment),
    ):
        if value is not None:
            _validate_single_line(obj, f"spec.{field_name}", value, errors)
    for key, value in config.environment.items():
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key) is None:
            errors.append(
                f"CronJob/{obj.name}: spec.environment key {key!r} must be a shell variable name"
            )
        _validate_single_line(obj, f"spec.environment.{key}", value, errors)


def _validate_single_line(
    obj: ConfigObject,
    label: str,
    value: object,
    errors: list[str],
) -> None:
    if any(char in str(value) for char in "\r\n"):
        errors.append(f"{obj.kind}/{obj.name}: {label} must be a single-line value")


def _render_cronjob(obj: ConfigObject, config: CronJobConfig) -> str:
    lines = [
        "# Generated by DROS. Manual changes will be overwritten.",
        f"# Resource: CronJob/{obj.name}",
    ]
    if config.comment:
        lines.append(f"# {config.comment}")
    for key, value in sorted(config.environment.items()):
        lines.append(f"{key}={shlex.quote(value)}")
    entry = f"{config.schedule} {config.user} {config.command}"
    if config.enabled:
        lines.append(entry)
    else:
        lines.append("# disabled")
        lines.append(f"# {entry}")
    lines.append("")
    return "\n".join(lines)


def _cron_path(name: str) -> str:
    safe_name = "".join(char if char.isalnum() or char in "._-" else "_" for char in name)
    return f"{CRON_D_DIR}/dros-{safe_name}"
