from __future__ import annotations

from pydantic import ValidationError

from dros.config_objects import ConfigObject, IpListUpdaterConfig
from dros.plugins.base import DrosPlugin, UpdateContext

CRON_PATH = "/etc/cron.d/dros-ip-list-updater"


def create_plugin() -> DrosPlugin:
    return DrosPlugin(
        name="ip_lists",
        config_kinds=frozenset({"IpListUpdater"}),
        managed_files=frozenset({CRON_PATH}),
        validation_hook=validate,
        update_hook=update,
    )


def validate(context: UpdateContext, objects: list[ConfigObject]) -> list[str]:
    errors: list[str] = []
    for obj in objects:
        try:
            config = context.configs.resolve_object(obj, IpListUpdaterConfig)
        except ValidationError as exc:
            for error in exc.errors():
                location = ".".join(str(part) for part in error["loc"])
                errors.append(f"{obj.kind}/{obj.name}: spec.{location}: {error['msg']}")
            continue
        try:
            _normalize_cron(config.cron)
        except ValueError as exc:
            errors.append(f"IpListUpdater/{obj.name}: spec.cron: {exc}")
    return errors


def update(context: UpdateContext, objects: list[ConfigObject]) -> None:
    selected = sorted(objects, key=lambda obj: obj.name)
    if not selected:
        return
    config = context.configs.resolve_object(selected[-1], IpListUpdaterConfig)
    if not config.enabled:
        context.executor.delete_file(CRON_PATH)
        return
    context.executor.write_file(CRON_PATH, _render_cron(config))


def _render_cron(config: IpListUpdaterConfig) -> str:
    return "\n".join(
        [
            "# Generated by DROS. Manual changes will be overwritten.",
            "SHELL=/bin/sh",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            (
                f"{_normalize_cron(config.cron)} root "
                "/usr/local/bin/gw ip-list update --verbose 1"
            ),
            "",
        ]
    )


def _normalize_cron(value: str) -> str:
    parts = value.split()
    if len(parts) == 3:
        minute, hour, day_of_week = parts
        parts = [minute, hour, "*", "*", day_of_week]
    if len(parts) != 5:
        raise ValueError("expected either 3 fields or 5 standard cron fields")
    if any("\n" in part for part in parts):
        raise ValueError("cron fields must be single-line values")
    return " ".join(parts)
