from __future__ import annotations

import shlex

from pydantic import ValidationError

from dros.config_objects import ConfigObject, DevGroupConfig, InterfaceConfig
from dros.plugins.base import DrosPlugin, UpdateContext

MANAGED_FILES = frozenset({"/etc/network/interfaces.d/dros-*.cfg"})


def create_plugin() -> DrosPlugin:
    return DrosPlugin(
        name="network.interfaces",
        depends_on=("network.core",),
        config_kinds=frozenset({"DevGroup", "Interface"}),
        managed_files=MANAGED_FILES,
        validation_hook=validate,
        update_hook=update,
    )


def validate(context: UpdateContext, objects: list[ConfigObject]) -> list[str]:
    errors: list[str] = []
    devgroups = _devgroups(context, errors)
    interface_names = {obj.name for obj in context.configs.by_kind("Interface")}

    for obj in objects:
        if obj.kind == "DevGroup":
            _validate_model(context, obj, DevGroupConfig, errors)
            continue
        if obj.kind != "Interface":
            continue
        config = _validate_model(context, obj, InterfaceConfig, errors)
        if config is None:
            continue
        errors.extend(_validate_interface(obj, config, devgroups, interface_names))
    return errors


def update(context: UpdateContext, objects: list[ConfigObject]) -> None:
    devgroups = _devgroups(context, [])
    interfaces = [obj for obj in objects if obj.kind == "Interface"]
    for obj in sorted(interfaces, key=_interface_sort_key):
        config = context.configs.resolve_object(obj, InterfaceConfig)
        path = f"/etc/network/interfaces.d/dros-{_safe_name(obj.name)}.cfg"
        changed = context.executor.write_file(path, _render_interface(obj.name, config, devgroups))
        if changed:
            context.executor.run(["ifdown", "--force", obj.name], check=False, real_only=True)
            context.executor.run(["ifup", obj.name], real_only=True)


def _devgroups(context: UpdateContext, errors: list[str]) -> dict[str, int]:
    groups: dict[str, int] = {}
    for obj in context.configs.by_kind("DevGroup"):
        config = _validate_model(context, obj, DevGroupConfig, errors)
        if config is None:
            continue
        groups[obj.name] = config.id
    return groups


def _validate_interface(
    obj: ConfigObject,
    config: InterfaceConfig,
    devgroups: dict[str, int],
    interface_names: set[str],
) -> list[str]:
    errors: list[str] = []
    if config.devgroup and config.devgroup not in devgroups:
        errors.append(f"Interface/{obj.name}: references undefined DevGroup/{config.devgroup}")
    if config.type == "vlan":
        if not config.parent:
            errors.append(f"Interface/{obj.name}: type vlan requires spec.parent")
        elif config.parent not in interface_names:
            errors.append(
                f"Interface/{obj.name}: parent Interface/{config.parent} is not defined"
            )
        if config.id is None:
            errors.append(f"Interface/{obj.name}: type vlan requires spec.id")
        elif not 1 <= config.id <= 4094:
            errors.append(
                f"Interface/{obj.name}: vlan id must be between 1 and 4094, got {config.id}"
            )
    return errors


def _validate_model(
    context: UpdateContext,
    obj: ConfigObject,
    model_type: type[DevGroupConfig] | type[InterfaceConfig],
    errors: list[str],
) -> DevGroupConfig | InterfaceConfig | None:
    try:
        return context.configs.resolve_object(obj, model_type)
    except ValidationError as exc:
        for error in exc.errors():
            location = ".".join(str(part) for part in error["loc"])
            errors.append(f"{obj.kind}/{obj.name}: spec.{location}: {error['msg']}")
        return None


def _render_interface(name: str, config: InterfaceConfig, devgroups: dict[str, int]) -> str:
    lines = [
        "# Generated by DROS. Manual changes will be overwritten.",
        f"auto {name}",
        *_address_family(name, config),
    ]
    if config.type == "bridge":
        _append_bridge(lines, config)
    elif config.type == "vlan":
        _append_vlan(lines, config)
    if config.devgroup:
        lines.append(f"  post-up ip link set dev {name} group {devgroups[config.devgroup]}")
    lines.append("")
    return "\n".join(lines)


def _address_family(name: str, config: InterfaceConfig) -> list[str]:
    if config.dhcp:
        lines = [f"iface {name} inet dhcp"]
    elif config.address:
        lines = [f"iface {name} inet static", f"  address {config.address}"]
    else:
        lines = [f"iface {name} inet manual"]

    if config.gateway:
        lines.append(f"  gateway {config.gateway}")
    for address in config.extra_addresses:
        lines.append(f"  up ip addr add {address} dev $IFACE")
        lines.append(f"  down ip addr del {address} dev $IFACE || true")
    return lines


def _append_bridge(lines: list[str], config: InterfaceConfig) -> None:
    ports = " ".join(config.ports) if config.ports else "none"
    lines.append(f"  bridge_ports {ports}")
    lines.append("  bridge_fd 0")
    if config.vlan_aware:
        lines.append("  bridge_vlan_aware yes")


def _append_vlan(lines: list[str], config: InterfaceConfig) -> None:
    parent = shlex.quote(str(config.parent))
    vlan_id = int(config.id or 0)
    lines.append(
        f"  pre-up ip link show dev {parent} >/dev/null 2>&1 || "
        f"{{ echo 'dros: vlan parent {parent} for $IFACE is missing' >&2; exit 1; }}"
    )
    lines.append(
        "  pre-up ip link show dev $IFACE >/dev/null 2>&1 || "
        f"ip link add link {parent} name $IFACE type vlan id {vlan_id}"
    )
    lines.append("  post-down ip link del dev $IFACE || true")


def _interface_sort_key(obj: ConfigObject) -> tuple[int, str]:
    type_order = {"eth": 0, "bridge": 1, "vlan": 2}
    iface_type = str(obj.spec.get("type", ""))
    return (type_order.get(iface_type, 50), obj.name)


def _safe_name(name: str) -> str:
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.:-")
    return "".join(char if char in allowed else "_" for char in name)
