from __future__ import annotations

import shlex
from collections.abc import Mapping
from dataclasses import dataclass

from pydantic import ValidationError

from dros.config_objects import (
    ConfigObject,
    FwMarkConfig,
    GatewayConfig,
    RouteConfig,
    RouteRuleConfig,
    RouteRuleSetConfig,
    RouteTableConfig,
)
from dros.ip_lists import IpListStore, load_ip_lists, looks_like_ip_list
from dros.plugins.base import BootstrapContext, DrosPlugin, UpdateContext

ROUTE_KINDS = frozenset({"FwMark", "Gateway", "RouteTable", "RouteRuleSet"})
UPDATE_ROUTE_SCRIPT = "tmp/update-route.sh"
MANAGED_FILES = frozenset(
    {
        "/etc/iproute2/rt_tables.d/dros.conf",
        "/etc/network/if-down.d/dros-route",
        "/etc/network/if-up.d/dros-route",
        "/etc/ppp/ip-down.d/dros-route",
        "/etc/ppp/ip-up.d/dros-route",
    }
)


@dataclass(frozen=True)
class GatewayRuntimeState:
    exists: bool
    up: bool


def create_plugin() -> DrosPlugin:
    return DrosPlugin(
        name="network.routing",
        depends_on=("network.interfaces",),
        config_kinds=ROUTE_KINDS,
        managed_files=MANAGED_FILES,
        bootstrap_hook=bootstrap,
        validation_hook=validate,
        update_hook=update,
        event_hooks=frozenset({"route-refresh", "iface-up", "iface-down", "ppp-up", "ppp-down"}),
    )


def bootstrap(context: BootstrapContext) -> None:
    for path in (
        "/etc/network/if-up.d/dros-route",
        "/etc/network/if-down.d/dros-route",
        "/etc/ppp/ip-up.d/dros-route",
        "/etc/ppp/ip-down.d/dros-route",
    ):
        context.executor.write_file(path, _route_hook_script(), mode=0o755)


def validate(context: UpdateContext, objects: list[ConfigObject]) -> list[str]:
    errors: list[str] = []
    gateways = _gateway_objects(context)
    route_tables = _route_table_object_map(context)
    fwmarks = _fwmark_objects(context)
    objects_to_validate = list(objects)
    if any(obj.kind == "Gateway" for obj in objects):
        objects_to_validate.extend(_route_table_objects(context))
    if any(obj.kind == "FwMark" for obj in objects):
        objects_to_validate.extend(_route_rule_set_objects(context))

    for obj in _unique_objects(objects_to_validate):
        if obj.kind == "FwMark":
            config = _validate_model(context, obj, FwMarkConfig, errors)
            if config is not None:
                _validate_fwmark(obj, config, errors)
        elif obj.kind == "Gateway":
            config = _validate_model(context, obj, GatewayConfig, errors)
            if config is not None:
                _validate_gateway(obj, config, errors)
        elif obj.kind == "RouteTable":
            config = _validate_model(context, obj, RouteTableConfig, errors)
            if config is not None:
                _validate_route_table(obj, config, gateways, context, errors)
        elif obj.kind == "RouteRuleSet":
            config = _validate_model(context, obj, RouteRuleSetConfig, errors)
            if config is not None:
                _validate_route_rule_set(obj, config, route_tables, fwmarks, context, errors)
    return errors


def update(context: UpdateContext, objects: list[ConfigObject]) -> None:
    _write_rt_tables(context)

    selected_tables = [obj for obj in objects if obj.kind == "RouteTable"]
    selected_rule_sets = [obj for obj in objects if obj.kind == "RouteRuleSet"]
    if any(obj.kind == "Gateway" for obj in objects):
        selected_tables = _route_table_objects(context)
    if any(obj.kind == "FwMark" for obj in objects):
        selected_rule_sets = _route_rule_set_objects(context)

    _apply_route_tables(context, selected_tables)

    for obj in sorted(selected_rule_sets, key=lambda item: item.name):
        config = context.configs.resolve_object(obj, RouteRuleSetConfig)
        _apply_route_rule_set(context, obj, config)


def handle_event(context: UpdateContext, _event: str, _iface: str | None = None) -> None:
    _write_rt_tables(context)
    _apply_route_tables(context, _route_table_objects(context))
    for obj in sorted(_route_rule_set_objects(context), key=lambda item: item.name):
        config = context.configs.resolve_object(obj, RouteRuleSetConfig)
        _apply_route_rule_set(context, obj, config)


def _write_rt_tables(context: UpdateContext) -> None:
    lines = ["# Generated by DROS. Manual changes will be overwritten."]
    for obj in sorted(_route_table_objects(context), key=lambda item: item.name):
        config = context.configs.resolve_object(obj, RouteTableConfig)
        if _is_decimal_table_id(config.table):
            lines.append(f"{config.table} {obj.name}")
    lines.append("")
    context.executor.write_file("/etc/iproute2/rt_tables.d/dros.conf", "\n".join(lines))


def _apply_route_tables(
    context: UpdateContext,
    objects: list[ConfigObject],
) -> None:
    selected = sorted(objects, key=lambda item: item.name)
    if not selected:
        return

    ip_lists = load_ip_lists(context.settings)
    runtime_states = _gateway_runtime_states(context)
    tables: list[tuple[str, str, list[str]]] = []
    unavailable_gateways: dict[str, list[str]] = {}
    for obj in selected:
        config = context.configs.resolve_object(obj, RouteTableConfig)
        ip_flag = _ip_flag(config.family)
        table = str(config.table)
        batch_lines: list[str] = []
        for index, route in enumerate(config.routes):
            for parts in _route_batch_parts(
                context,
                obj,
                index,
                route,
                table,
                ip_lists,
                config.family,
                runtime_states,
                unavailable_gateways,
            ):
                batch_lines.append(_batch_line(parts))
        tables.append((ip_flag, table, batch_lines))

    _warn_unavailable_gateways(context, unavailable_gateways)
    script_path = context.settings.paths.run / UPDATE_ROUTE_SCRIPT
    context.executor.write_file(
        script_path,
        _render_update_route_script(tables),
        mode=0o755,
        show_diff=False,
    )
    context.executor.run(["sh", str(script_path)], real_only=True, quiet=True)


def _route_batch_parts(
    context: UpdateContext,
    obj: ConfigObject,
    index: int,
    route: RouteConfig,
    table: str,
    ip_lists: IpListStore,
    family: str,
    runtime_states: Mapping[str, GatewayRuntimeState],
    unavailable_gateways: dict[str, list[str]],
) -> list[list[str]]:
    if route.raw:
        return [["route", *shlex.split(route.raw), "table", table]]

    destinations = _route_destinations(context, obj, index, route, family, ip_lists)
    if route.type != "route":
        return [
            ["route", "replace", route.type, destination, "table", table]
            for destination in destinations
        ]

    gateway = _require_gateway(context, obj, route.gateway)
    if not gateway_is_available(_gateway_devs(gateway), runtime_states):
        unavailable_gateways.setdefault(str(route.gateway), []).append(
            f"RouteTable/{obj.name}[{index}]"
        )
        return []
    gateway_parts, gateway_metric = _gateway_parts(gateway)
    metric = route.metric if route.metric is not None else gateway_metric
    rendered: list[list[str]] = []
    for destination in destinations:
        parts = ["route", "replace", destination, *gateway_parts]
        if metric is not None:
            parts.extend(["metric", str(metric)])
        parts.extend(["table", table])
        rendered.append(parts)
    return rendered


def _apply_route_rule_set(
    context: UpdateContext,
    obj: ConfigObject,
    config: RouteRuleSetConfig,
) -> None:
    ip_flag = _ip_flag(config.family)
    start = str(config.managed_priority.start)
    end = str(config.managed_priority.end)
    context.executor.run(
        ["sh", "-c", _flush_rules_script(), "sh", ip_flag, start, end],
        check=False,
        real_only=True,
        quiet=True,
    )
    for rule in sorted(config.rules, key=lambda item: item.priority):
        context.executor.run(
            ["ip", ip_flag, "rule", "add", *_rule_parts(context, obj, rule)],
            real_only=True,
            quiet=True,
        )


def _rule_parts(context: UpdateContext, obj: ConfigObject, rule: RouteRuleConfig) -> list[str]:
    if rule.raw:
        return ["priority", str(rule.priority), *shlex.split(rule.raw)]

    parts = ["priority", str(rule.priority)]
    for value, name in (
        (rule.from_, "from"),
        (rule.to, "to"),
        (rule.iif, "iif"),
        (rule.oif, "oif"),
        (rule.uidrange, "uidrange"),
    ):
        if value:
            parts.extend([name, value])
    fwmark = _resolve_rule_fwmark(context, obj, rule)
    if fwmark:
        parts.extend(["fwmark", fwmark])
    if rule.lookup is not None:
        parts.extend(["lookup", _resolve_lookup(context, rule.lookup)])
    if rule.suppress_prefixlength is not None:
        parts.extend(["suppress_prefixlength", str(rule.suppress_prefixlength)])
    return parts


def _validate_fwmark(obj: ConfigObject, config: FwMarkConfig, errors: list[str]) -> None:
    for field_name, value in (("mark", config.mark), ("mask", config.mask)):
        try:
            _parse_u32(value)
        except ValueError:
            errors.append(f"FwMark/{obj.name}: spec.{field_name} must be a 32-bit integer")


def _validate_gateway(obj: ConfigObject, config: GatewayConfig, errors: list[str]) -> None:
    has_single = bool(config.dev)
    has_nexthops = bool(config.nexthops)
    if has_single == has_nexthops:
        errors.append(f"Gateway/{obj.name}: exactly one of spec.dev or spec.nexthops is required")
    if config.metric is not None and config.metric < 0:
        errors.append(f"Gateway/{obj.name}: spec.metric must be non-negative")
    for index, hop in enumerate(config.nexthops):
        if hop.weight is not None and hop.weight <= 0:
            errors.append(f"Gateway/{obj.name}: spec.nexthops[{index}].weight must be positive")


def _validate_route_table(
    obj: ConfigObject,
    config: RouteTableConfig,
    gateways: dict[str, ConfigObject],
    context: UpdateContext,
    errors: list[str],
) -> None:
    if isinstance(config.table, int) and config.table <= 0:
        errors.append(f"RouteTable/{obj.name}: spec.table must be positive")
    for index, route in enumerate(config.routes):
        if route.raw:
            continue
        if route.type == "route":
            if not route.gateway:
                errors.append(f"RouteTable/{obj.name}: spec.routes[{index}].gateway is required")
            elif route.gateway not in gateways:
                errors.append(
                    f"RouteTable/{obj.name}: spec.routes[{index}] references "
                    f"Gateway/{route.gateway} is not defined"
                )
            else:
                gateway_obj = gateways[route.gateway]
                gateway = _validate_model(context, gateway_obj, GatewayConfig, errors)
                if gateway is not None:
                    _validate_gateway(gateway_obj, gateway, errors)
        if route.metric is not None and route.metric < 0:
            errors.append(f"RouteTable/{obj.name}: spec.routes[{index}].metric must be non-negative")


def _validate_route_rule_set(
    obj: ConfigObject,
    config: RouteRuleSetConfig,
    route_tables: dict[str, ConfigObject],
    fwmarks: dict[str, ConfigObject],
    context: UpdateContext,
    errors: list[str],
) -> None:
    start = config.managed_priority.start
    end = config.managed_priority.end
    if start > end:
        errors.append(f"RouteRuleSet/{obj.name}: spec.managedPriority.start must be <= end")
    priorities: set[int] = set()
    for index, rule in enumerate(config.rules):
        if rule.priority in priorities:
            errors.append(
                f"RouteRuleSet/{obj.name}: spec.rules[{index}].priority duplicates "
                f"{rule.priority}"
            )
        priorities.add(rule.priority)
        if not start <= rule.priority <= end:
            errors.append(
                f"RouteRuleSet/{obj.name}: spec.rules[{index}].priority must be within "
                f"{start}-{end}"
            )
        if rule.fw_mark and rule.fwmark:
            errors.append(f"RouteRuleSet/{obj.name}: spec.rules[{index}] cannot set both fwMark and fwmark")
        if not rule.raw and rule.lookup is None:
            errors.append(f"RouteRuleSet/{obj.name}: spec.rules[{index}].lookup is required")
        if rule.fw_mark:
            fwmark = fwmarks.get(rule.fw_mark)
            if fwmark is None:
                errors.append(
                    f"RouteRuleSet/{obj.name}: spec.rules[{index}] references "
                    f"FwMark/{rule.fw_mark} is not defined"
                )
            else:
                config_obj = context.configs.resolve_object(fwmark, FwMarkConfig)
                _validate_fwmark(fwmark, config_obj, errors)
        if isinstance(rule.lookup, str) and rule.lookup in route_tables:
            table = context.configs.resolve_object(route_tables[rule.lookup], RouteTableConfig)
            if isinstance(table.table, int) and table.table <= 0:
                errors.append(f"RouteRuleSet/{obj.name}: lookup RouteTable/{rule.lookup} has invalid table")


def _validate_model(
    context: UpdateContext,
    obj: ConfigObject,
    model_type: type[FwMarkConfig]
    | type[GatewayConfig]
    | type[RouteTableConfig]
    | type[RouteRuleSetConfig],
    errors: list[str],
) -> FwMarkConfig | GatewayConfig | RouteTableConfig | RouteRuleSetConfig | None:
    try:
        return context.configs.resolve_object(obj, model_type)
    except ValidationError as exc:
        for error in exc.errors():
            location = ".".join(str(part) for part in error["loc"])
            errors.append(f"{obj.kind}/{obj.name}: spec.{location}: {error['msg']}")
        return None


def _gateway_parts(config: GatewayConfig) -> tuple[list[str], int | None]:
    if config.nexthops:
        parts: list[str] = []
        for hop in config.nexthops:
            parts.append("nexthop")
            if hop.via:
                parts.extend(["via", hop.via])
            parts.extend(["dev", hop.dev])
            if hop.onlink:
                parts.append("onlink")
            if hop.weight:
                parts.extend(["weight", str(hop.weight)])
        return parts, config.metric

    parts = []
    if config.via:
        parts.extend(["via", config.via])
    parts.extend(["dev", str(config.dev)])
    if config.onlink:
        parts.append("onlink")
    return parts, config.metric


def _gateway_devs(config: GatewayConfig) -> tuple[str, ...]:
    if config.nexthops:
        return tuple(hop.dev for hop in config.nexthops)
    return (config.dev,) if config.dev else ()


def gateway_is_available(
    devs: tuple[str, ...],
    runtime_states: Mapping[str, GatewayRuntimeState],
) -> bool:
    if not runtime_states:
        return True
    for dev in devs:
        state = runtime_states.get(dev)
        if state is None or not state.exists or not state.up:
            return False
    return True


def _require_gateway(context: UpdateContext, obj: ConfigObject, name: str | None) -> GatewayConfig:
    if not name:
        raise ValueError(f"RouteTable/{obj.name}: route gateway is required")
    gateway = context.configs.get("Gateway", name)
    if gateway is None:
        raise ValueError(f"RouteTable/{obj.name}: Gateway/{name} is not defined")
    return context.configs.resolve_object(gateway, GatewayConfig)


def _resolve_rule_fwmark(
    context: UpdateContext,
    obj: ConfigObject,
    rule: RouteRuleConfig,
) -> str | None:
    if rule.fw_mark:
        return _format_fwmark_resource(context, obj, rule.fw_mark)
    if rule.fwmark:
        if context.configs.get("FwMark", rule.fwmark) is not None:
            return _format_fwmark_resource(context, obj, rule.fwmark)
        return rule.fwmark
    return None


def _format_fwmark_resource(context: UpdateContext, obj: ConfigObject, name: str) -> str:
    resource = context.configs.get("FwMark", name)
    if resource is None:
        raise ValueError(f"{obj.kind}/{obj.name}: FwMark/{name} is not defined")
    config = context.configs.resolve_object(resource, FwMarkConfig)
    return f"{_format_u32(config.mark)}/{_format_u32(config.mask)}"


def _resolve_lookup(context: UpdateContext, lookup: int | str) -> str:
    if isinstance(lookup, str):
        table = context.configs.get("RouteTable", lookup)
        if table is not None:
            config = context.configs.resolve_object(table, RouteTableConfig)
            return str(config.table)
    return str(lookup)


def _normalize_destination(value: str | None, obj: ConfigObject) -> str:
    if not value:
        raise ValueError(f"RouteTable/{obj.name}: route destination is required")
    if value == "default6":
        return "default"
    return value


def _route_destinations(
    context: UpdateContext,
    obj: ConfigObject,
    index: int,
    route: RouteConfig,
    family: str,
    ip_lists: IpListStore,
) -> list[str]:
    destination = _normalize_destination(route.to, obj)
    if not looks_like_ip_list(destination):
        return [destination]
    routes, warnings = ip_lists.resolve(destination, family)  # type: ignore[arg-type]
    if warnings:
        for warning in warnings:
            _warn(context, f"RouteTable/{obj.name}: spec.routes[{index}]: {warning}; skipped")
        return []
    if not routes:
        _warn(
            context,
            f"RouteTable/{obj.name}: spec.routes[{index}]: ip list {destination!r} is empty; skipped",
        )
    return routes


def _fwmark_objects(context: UpdateContext) -> dict[str, ConfigObject]:
    return {obj.name: obj for obj in context.configs.by_kind("FwMark")}


def _gateway_objects(context: UpdateContext) -> dict[str, ConfigObject]:
    return {obj.name: obj for obj in context.configs.by_kind("Gateway")}


def _route_table_objects(context: UpdateContext) -> list[ConfigObject]:
    return context.configs.by_kind("RouteTable")


def _route_table_object_map(context: UpdateContext) -> dict[str, ConfigObject]:
    return {obj.name: obj for obj in context.configs.by_kind("RouteTable")}


def _route_rule_set_objects(context: UpdateContext) -> list[ConfigObject]:
    return context.configs.by_kind("RouteRuleSet")


def _unique_objects(objects: list[ConfigObject]) -> list[ConfigObject]:
    seen: set[tuple[str, str]] = set()
    result: list[ConfigObject] = []
    for obj in objects:
        key = (obj.kind, obj.name)
        if key in seen:
            continue
        seen.add(key)
        result.append(obj)
    return result


def _ip_flag(family: str) -> str:
    return "-6" if family == "ipv6" else "-4"


def _is_decimal_table_id(value: object) -> bool:
    if isinstance(value, int):
        return value > 0
    return str(value).isdigit()


def _parse_u32(value: object) -> int:
    parsed = int(str(value), 0) if not isinstance(value, int) else value
    if not 0 <= parsed <= 0xFFFFFFFF:
        raise ValueError(f"not a 32-bit value: {value}")
    return parsed


def _format_u32(value: object) -> str:
    return f"0x{_parse_u32(value):08x}"


def _gateway_runtime_states(context: UpdateContext) -> dict[str, GatewayRuntimeState]:
    if not context.executor.is_real_root:
        return {}
    output = context.executor.output(["ip", "-o", "link", "show"], default="", real_only=True)
    states: dict[str, GatewayRuntimeState] = {}
    for line in output.splitlines():
        parts = line.split(":", 2)
        if len(parts) < 3:
            continue
        dev = parts[1].strip().split("@", 1)[0]
        flags = ""
        if "<" in parts[2] and ">" in parts[2]:
            flags = parts[2].split("<", 1)[1].split(">", 1)[0]
        states[dev] = GatewayRuntimeState(exists=True, up="UP" in flags.split(","))
    return states


def _render_update_route_script(tables: list[tuple[str, str, list[str]]]) -> str:
    lines = [
        "#!/bin/sh",
        "# Generated by DROS. Manual changes will be overwritten.",
        "set -eu",
        'tmp_dir="$(mktemp -d)"',
        "trap 'rm -rf \"$tmp_dir\"' EXIT",
        "",
    ]
    for index, (ip_flag, table, batch_lines) in enumerate(tables):
        quoted_table = shlex.quote(table)
        lines.append(f"ip {ip_flag} route flush table {quoted_table} 2>/dev/null || true")
        if batch_lines:
            marker = f"DROS_ROUTE_BATCH_{index}"
            lines.append(f'batch="$tmp_dir/route-{index}.batch"')
            lines.append(f"cat > \"$batch\" <<'{marker}'")
            lines.extend(batch_lines)
            lines.append(marker)
            lines.append(f'ip {ip_flag} -batch "$batch"')
        lines.append("")
    return "\n".join(lines)


def _batch_line(parts: list[str]) -> str:
    return " ".join(parts)


def _warn(context: UpdateContext, message: str) -> None:
    if context.executor.verbose >= 1:
        context.executor.console.print(f"warning: {message}", markup=False)


def _warn_unavailable_gateways(
    context: UpdateContext,
    unavailable_gateways: dict[str, list[str]],
) -> None:
    for gateway_name, route_refs in unavailable_gateways.items():
        shown = ", ".join(route_refs[:5])
        if len(route_refs) > 5:
            shown = f"{shown}, +{len(route_refs) - 5} more"
        _warn(
            context,
            f"Gateway/{gateway_name} is unavailable; skipped {len(route_refs)} route(s): {shown}",
        )


def _flush_rules_script() -> str:
    return r'''
family="$1"
start="$2"
end="$3"
ip "$family" rule show | while IFS= read -r line; do
  priority="${line%%:*}"
  case "$priority" in
    ''|*[!0-9]*) continue ;;
  esac
  if [ "$priority" -ge "$start" ] && [ "$priority" -le "$end" ]; then
    ip "$family" rule del priority "$priority" 2>/dev/null || true
  fi
done
'''


def _route_hook_script() -> str:
    return "\n".join(
        [
            "#!/bin/sh",
            "# Generated by DROS. Manual changes will be overwritten.",
            "set -eu",
            'IFACE="${IFACE:-${1:-}}"',
            'case "$IFACE" in',
            '  ""|-*) exec /usr/local/bin/gw hook route-refresh --verbose 0 ;;',
            '  *) exec /usr/local/bin/gw hook route-refresh "$IFACE" --verbose 0 ;;',
            "esac",
            "",
        ]
    )
