from __future__ import annotations

import re
from typing import Any

from pydantic import ValidationError

from dros.config_objects import (
    ConfigObject,
    DevGroupConfig,
    FirewallConfig,
    FwMarkConfig,
)
from dros.plugins.base import DrosPlugin, UpdateContext

NFTABLES_CONF = "/etc/nftables.conf"
FIREWALL_PATH = "/etc/dros/nftables.d/10-firewall.nft"
FILTER_TABLE = "dros_filter"
ROUTE_TABLE = "dros_route"
NAT_TABLE = "dros_nat"


def create_plugin() -> DrosPlugin:
    return DrosPlugin(
        name="network.firewall",
        depends_on=("network.interfaces", "network.routing"),
        config_kinds=frozenset({"Firewall"}),
        managed_files=frozenset({NFTABLES_CONF, FIREWALL_PATH}),
        validation_hook=validate,
        update_hook=update,
    )


def validate(context: UpdateContext, objects: list[ConfigObject]) -> list[str]:
    errors: list[str] = []
    devgroups = _devgroups(context, errors)
    fwmarks = _fwmarks(context)
    for obj in objects:
        config = _validate_model(context, obj, errors)
        if config is None:
            continue
        _validate_defaults(obj, config.defaults, errors)
        _validate_interface_rules(obj, config.interface_rules, devgroups, errors)
        _validate_firewall_rules(obj, config.firewall_rules, devgroups, errors)
        _validate_nat_rules(obj, config.nat_rules, devgroups, errors)
        _validate_mark_rules(obj, config.mark_rules, devgroups, fwmarks, context, errors)
    return errors


def update(context: UpdateContext, objects: list[ConfigObject]) -> None:
    firewalls = sorted(objects, key=lambda item: item.name)
    context.executor.ensure_dir("/etc/dros/nftables.d")
    entrypoint_changed = context.executor.write_file(NFTABLES_CONF, _render_nftables_conf())
    rules_changed = context.executor.write_file(FIREWALL_PATH, _render_firewall(context, firewalls))
    changed = entrypoint_changed or rules_changed
    if changed:
        context.executor.run(["nft", "-f", NFTABLES_CONF], real_only=True)
        context.executor.run(["systemctl", "enable", "--now", "nftables.service"], real_only=True)


def _render_nftables_conf() -> str:
    return 'flush ruleset\ninclude "/etc/dros/nftables.d/*.nft"\n'


def _render_firewall(context: UpdateContext, objects: list[ConfigObject]) -> str:
    configs = [(obj, context.configs.resolve_object(obj, FirewallConfig)) for obj in objects]
    default_config = _default_firewall_config(context, configs)
    lines = [
        "# Generated by DROS. Manual changes will be overwritten.",
        _render_main(default_config.defaults),
    ]
    for obj, config in configs:
        lines.append(f"# Firewall/{obj.name}")
        lines.append(_render_policy(context, config))
        lines.append(_render_nat(context, config))
        lines.append(_render_mark(context, config))
    return "\n".join(lines)


def _default_firewall_config(
    context: UpdateContext,
    configs: list[tuple[ConfigObject, FirewallConfig]],
) -> FirewallConfig:
    for obj, config in configs:
        if obj.name == "main":
            return config
    if configs:
        return configs[0][1]
    return context.configs.resolve("Firewall", FirewallConfig)


def _render_main(defaults: dict[str, Any]) -> str:
    input_policy = str(defaults.get("inputPolicy", "drop"))
    forward_policy = str(defaults.get("forwardPolicy", "drop"))
    output_policy = str(defaults.get("outputPolicy", "accept"))
    allow_essential_icmp = bool(defaults.get("allowEssentialIcmp", True))
    allow_essential_icmpv6 = defaults.get("allowIcmpv6")
    if allow_essential_icmpv6 is None:
        allow_essential_icmpv6 = allow_essential_icmp
    lines = [
        f"table inet {FILTER_TABLE} {{",
        "  chain input {",
        f"    type filter hook input priority filter; policy {input_policy};",
        "    jump input_pre",
        "    jump input_auto",
        "    jump input_user",
        "    jump input_post",
        "    jump input_policy",
        "  }",
        "",
        "  chain output {",
        f"    type filter hook output priority filter; policy {output_policy};",
        "    jump output_user",
        "    jump output_policy",
        "  }",
        "",
        "  chain forward {",
        f"    type filter hook forward priority filter; policy {forward_policy};",
        "    jump forward_pre",
        "    jump portmap_forward",
        "    jump forward_auto",
        "    jump forward_user",
        "    jump forward_post",
        "    jump forward_policy",
        "  }",
        "",
        "  chain input_pre {",
    ]
    if defaults.get("allowLoopback", True):
        lines.append("    iif lo accept")
    if defaults.get("allowEstablished", True):
        lines.append("    ct state established,related accept")
        lines.append("    ct state invalid drop")
    if allow_essential_icmp:
        lines.append(
            "    meta nfproto ipv4 icmp type "
            "{ destination-unreachable, time-exceeded, parameter-problem } accept"
        )
    if allow_essential_icmpv6:
        lines.append(
            "    meta nfproto ipv6 icmpv6 type "
            "{ destination-unreachable, packet-too-big, time-exceeded, "
            "parameter-problem, nd-neighbor-solicit, nd-neighbor-advert } accept"
        )
    lines.extend(
        [
            "  }",
            "  chain input_auto { }",
            "  chain input_user { }",
            "  chain input_post { }",
            "  chain input_policy { }",
            "  chain output_user { }",
            "  chain output_policy { }",
            "",
            "  chain forward_pre {",
        ]
    )
    if defaults.get("allowEstablished", True):
        lines.append("    ct state established,related accept")
        lines.append("    ct state invalid drop")
    if defaults.get("clampMss", True):
        lines.append("    tcp flags syn tcp option maxseg size set rt mtu")
    lines.extend(
        [
            "  }",
            "  chain portmap_forward { }",
            "  chain forward_auto { }",
            "  chain forward_user { }",
            "  chain forward_post { }",
            "  chain forward_policy { }",
            "}",
            "",
            f"table inet {ROUTE_TABLE} {{",
            "  chain output {",
            "    type route hook output priority mangle;",
            "    jump mark_output",
            "  }",
            "",
            "  chain prerouting {",
            "    type filter hook prerouting priority mangle;",
            "    jump mark_prerouting",
            "  }",
            "",
            "  chain mark_output { }",
            "  chain mark_prerouting { }",
            "}",
            "",
            f"table inet {NAT_TABLE} {{",
            "  chain output {",
            "    type nat hook output priority dstnat;",
            "    jump dnat_output",
            "  }",
            "",
            "  chain prerouting {",
            "    type nat hook prerouting priority dstnat;",
            "    jump dnat_prerouting",
            "  }",
            "",
            "  chain postrouting {",
            "    type nat hook postrouting priority srcnat;",
            "    jump snat_postrouting",
            "    jump masquerade_postrouting",
            "  }",
            "",
            "  chain dnat_output { }",
            "  chain dnat_prerouting { }",
            "  chain snat_postrouting { }",
            "  chain masquerade_postrouting { }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def _render_policy(context: UpdateContext, config: FirewallConfig) -> str:
    lines: list[str] = []
    for item in config.interface_rules:
        subject = str(item["subject"])
        selector = _subject_selector(context, subject, direction="iif")
        output_selector = _subject_selector(context, subject, direction="oif")
        input_rule = item.get("input") or {}
        ping = input_rule.get("ping")
        if ping is not None:
            verdict = "accept" if ping else "drop"
            lines.append(
                f"add rule inet {FILTER_TABLE} input_auto {selector} "
                f"meta nfproto ipv4 icmp type echo-request {verdict}"
            )
            lines.append(
                f"add rule inet {FILTER_TABLE} input_auto {selector} "
                f"meta nfproto ipv6 icmpv6 type echo-request {verdict}"
            )
        if input_rule.get("dhcpv6Client"):
            lines.append(
                f"add rule inet {FILTER_TABLE} input_auto {selector} "
                "udp sport 547 udp dport 546 accept"
            )
        for service in input_rule.get("services", []):
            lines.append(
                f"add rule inet {FILTER_TABLE} input_auto {selector} "
                f"{_service_match(str(service))} accept"
            )
        if input_rule.get("policy"):
            lines.append(
                f"add rule inet {FILTER_TABLE} input_policy {selector} "
                f"{input_rule['policy']}"
            )

        forward_rule = item.get("forward") or {}
        for target in forward_rule.get("allowTo", []):
            target_selector = _subject_selector(context, str(target), direction="oif")
            lines.append(
                f"add rule inet {FILTER_TABLE} forward_auto {selector} "
                f"{target_selector} accept"
            )
        if forward_rule.get("denyPrivateNetworks"):
            lines.append(
                f"add rule inet {FILTER_TABLE} forward_auto {selector} "
                "ip daddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } drop"
            )
        if forward_rule.get("policy"):
            lines.append(
                f"add rule inet {FILTER_TABLE} forward_policy {selector} "
                f"{forward_rule['policy']}"
            )

        output_rule = item.get("output") or {}
        if output_rule.get("policy"):
            lines.append(
                f"add rule inet {FILTER_TABLE} output_policy {output_selector} "
                f"{output_rule['policy']}"
            )
        if output_rule.get("masquerade"):
            lines.append(
                f"add rule inet {NAT_TABLE} masquerade_postrouting "
                f"{output_selector} meta nfproto ipv4 masquerade"
            )

    for item in config.firewall_rules:
        chain = f"{item['chain']}_user"
        rule = _resolve_raw_devgroups(context, str(item["rule"]))
        lines.append(f"add rule inet {FILTER_TABLE} {chain} {rule}")
    lines.append("")
    return "\n".join(lines)


def _render_nat(context: UpdateContext, config: FirewallConfig) -> str:
    lines: list[str] = []
    for item in config.nat_rules:
        if item.get("rawRule"):
            chain = _nat_chain(str(item["type"]))
            raw_rule = _resolve_raw_devgroups(context, str(item["rawRule"]))
            lines.append(f"add rule inet {NAT_TABLE} {chain} {raw_rule}")
            if item.get("forwardAllowRule"):
                forward_rule = _resolve_raw_devgroups(context, str(item["forwardAllowRule"]))
                lines.append(f"add rule inet {FILTER_TABLE} portmap_forward {forward_rule}")
            continue

        kind = str(item["type"])
        family = str(item.get("family", "ip"))
        match = _nat_match(context, item)
        if kind == "portmap":
            to_port = f":{item['toPort']}" if item.get("toPort") is not None else ""
            lines.append(
                f"add rule inet {NAT_TABLE} dnat_prerouting {match} "
                f"{item['proto']} dport {_port_set(item['dport'])} "
                f"dnat to {item['to']}{to_port}"
            )
            forward_port = _port_set(item.get("toPort", item["dport"]))
            lines.append(
                f"add rule inet {FILTER_TABLE} portmap_forward {match} "
                f"{family} daddr {item['to']} {item['proto']} dport {forward_port} accept"
            )
            if item.get("hairpin"):
                lines.append(_render_hairpin(item, family))
        elif kind == "ipmap":
            lines.append(f"add rule inet {NAT_TABLE} dnat_prerouting {match} dnat to {item['to']}")
            lines.append(f"add rule inet {FILTER_TABLE} portmap_forward {match} accept")
        elif kind == "snat":
            lines.append(f"add rule inet {NAT_TABLE} snat_postrouting {match} snat to {item['to']}")
        elif kind == "masquerade":
            lines.append(f"add rule inet {NAT_TABLE} masquerade_postrouting {match} masquerade")
    lines.append("")
    return "\n".join(lines)


def _render_mark(context: UpdateContext, config: FirewallConfig) -> str:
    lines: list[str] = []
    for item in config.mark_rules:
        for chain in item.get("chains", ["prerouting", "output"]):
            nft_chain = "mark_prerouting" if chain == "prerouting" else "mark_output"
            for rule in item.get("rules", []):
                resolved_rule = _resolve_raw_devgroups(context, str(rule))
                lines.append(f"add rule inet {ROUTE_TABLE} {nft_chain} {resolved_rule}")
            for rule in _structured_mark_rules(context, item, chain=str(chain)):
                lines.append(f"add rule inet {ROUTE_TABLE} {nft_chain} {rule}")
    lines.append("")
    return "\n".join(lines)


def _structured_mark_rules(context: UpdateContext, item: dict[str, Any], *, chain: str) -> list[str]:
    match = item.get("match")
    if not match:
        return []
    mark_expr = _mark_set_expr_for_rule(context, item)
    ingress_match = _mark_ingress_match(context, match)
    if ingress_match and chain == "output":
        return []
    rules: list[str] = []
    if match.get("tcpDports"):
        rules.append(f"{ingress_match} tcp dport {_port_set(match['tcpDports'])} {mark_expr}".strip())
    if match.get("udpDports"):
        rules.append(f"{ingress_match} udp dport {_port_set(match['udpDports'])} {mark_expr}".strip())
    if match.get("icmp"):
        rules.append(f"{ingress_match} meta nfproto ipv4 meta l4proto icmp {mark_expr}".strip())
    if not rules and ingress_match:
        rules.append(f"{ingress_match} {mark_expr}")
    return rules


def _validate_model(
    context: UpdateContext,
    obj: ConfigObject,
    errors: list[str],
) -> FirewallConfig | None:
    try:
        return context.configs.resolve_object(obj, FirewallConfig)
    except ValidationError as exc:
        for error in exc.errors():
            location = ".".join(str(part) for part in error["loc"])
            errors.append(f"{obj.kind}/{obj.name}: spec.{location}: {error['msg']}")
        return None


def _validate_defaults(obj: ConfigObject, defaults: dict[str, Any], errors: list[str]) -> None:
    for field in ("inputPolicy", "forwardPolicy", "outputPolicy"):
        value = defaults.get(field)
        if value is not None and value not in {"accept", "drop"}:
            errors.append(f"Firewall/{obj.name}: spec.defaults.{field} must be accept or drop")


def _validate_interface_rules(
    obj: ConfigObject,
    rules: list[dict[str, Any]],
    devgroups: dict[str, int],
    errors: list[str],
) -> None:
    for index, item in enumerate(rules):
        subject = item.get("subject")
        if not subject:
            errors.append(f"Firewall/{obj.name}: spec.interfaceRules[{index}].subject is required")
        else:
            _validate_subject(obj, f"spec.interfaceRules[{index}].subject", str(subject), devgroups, errors)
        input_rule = item.get("input") or {}
        for service in input_rule.get("services", []):
            try:
                _service_match(str(service))
            except ValueError as exc:
                errors.append(f"Firewall/{obj.name}: spec.interfaceRules[{index}].input.services: {exc}")


def _validate_firewall_rules(
    obj: ConfigObject,
    rules: list[dict[str, Any]],
    devgroups: dict[str, int],
    errors: list[str],
) -> None:
    for index, item in enumerate(rules):
        chain = item.get("chain")
        if chain not in {"input", "output", "forward"}:
            errors.append(f"Firewall/{obj.name}: spec.firewallRules[{index}].chain is invalid")
        if not item.get("rule"):
            errors.append(f"Firewall/{obj.name}: spec.firewallRules[{index}].rule is required")
        else:
            _validate_raw_devgroups(
                obj,
                f"spec.firewallRules[{index}].rule",
                str(item["rule"]),
                devgroups,
                errors,
            )


def _validate_nat_rules(
    obj: ConfigObject,
    rules: list[dict[str, Any]],
    devgroups: dict[str, int],
    errors: list[str],
) -> None:
    for index, item in enumerate(rules):
        kind = item.get("type")
        if kind not in {"portmap", "ipmap", "snat", "masquerade", "raw"}:
            errors.append(f"Firewall/{obj.name}: spec.natRules[{index}].type is invalid")
        if item.get("rawRule"):
            _validate_raw_devgroups(
                obj,
                f"spec.natRules[{index}].rawRule",
                str(item["rawRule"]),
                devgroups,
                errors,
            )
            continue
        if kind == "portmap":
            if not item.get("proto") or item.get("dport") is None or not item.get("to"):
                errors.append(
                    f"Firewall/{obj.name}: spec.natRules[{index}] "
                    "portmap requires proto, dport, and to"
                )
        if item.get("iif"):
            _validate_subject(obj, f"spec.natRules[{index}].iif", str(item["iif"]), devgroups, errors)
        if item.get("oif"):
            _validate_subject(obj, f"spec.natRules[{index}].oif", str(item["oif"]), devgroups, errors)


def _validate_mark_rules(
    obj: ConfigObject,
    rules: list[dict[str, Any]],
    devgroups: dict[str, int],
    fwmarks: dict[str, ConfigObject],
    context: UpdateContext,
    errors: list[str],
) -> None:
    for index, item in enumerate(rules):
        fwmark_name = item.get("fwMark")
        if fwmark_name:
            fwmark_obj = fwmarks.get(str(fwmark_name))
            if fwmark_obj is None:
                errors.append(
                    f"Firewall/{obj.name}: spec.markRules[{index}] references "
                    f"undefined FwMark/{fwmark_name}"
                )
            else:
                _validate_fwmark_obj(context, fwmark_obj, errors)
        elif item.get("match") and (item.get("mark") is None or item.get("mask") is None):
            errors.append(
                f"Firewall/{obj.name}: spec.markRules[{index}] requires fwMark "
                "or both mark and mask when match is set"
            )
        if item.get("match"):
            match = item["match"]
            for field in ("iifGroup", "iif_group"):
                for value in _list_values(match.get(field, [])):
                    subject = value if value.startswith("devgroup/") else f"devgroup/{value}"
                    _validate_subject(
                        obj,
                        f"spec.markRules[{index}].match.{field}",
                        subject,
                        devgroups,
                        errors,
                    )


def _validate_subject(
    obj: ConfigObject,
    field: str,
    value: str,
    devgroups: dict[str, int],
    errors: list[str],
) -> None:
    if value.startswith("devgroup/"):
        name = value.split("/", 1)[1]
        if name not in devgroups:
            errors.append(f"Firewall/{obj.name}: {field} references undefined DevGroup/{name}")


def _validate_raw_devgroups(
    obj: ConfigObject,
    field: str,
    rule: str,
    devgroups: dict[str, int],
    errors: list[str],
) -> None:
    for match in _raw_devgroup_references(rule):
        name = match.removeprefix("devgroup/")
        if name not in devgroups and not name.isdigit():
            errors.append(f"Firewall/{obj.name}: {field} references undefined DevGroup/{name}")


def _validate_fwmark_obj(context: UpdateContext, obj: ConfigObject, errors: list[str]) -> None:
    try:
        config = context.configs.resolve_object(obj, FwMarkConfig)
        _parse_u32(config.mark)
        _parse_u32(config.mask)
    except (ValidationError, ValueError):
        errors.append(f"FwMark/{obj.name}: spec.mark and spec.mask must be 32-bit integers")


def _devgroups(context: UpdateContext, errors: list[str]) -> dict[str, int]:
    groups: dict[str, int] = {}
    for obj in context.configs.by_kind("DevGroup"):
        try:
            config = context.configs.resolve_object(obj, DevGroupConfig)
        except ValidationError as exc:
            for error in exc.errors():
                location = ".".join(str(part) for part in error["loc"])
                errors.append(f"DevGroup/{obj.name}: spec.{location}: {error['msg']}")
            continue
        groups[obj.name] = config.id
    return groups


def _fwmarks(context: UpdateContext) -> dict[str, ConfigObject]:
    return {obj.name: obj for obj in context.configs.by_kind("FwMark")}


def _subject_selector(context: UpdateContext, value: str, *, direction: str) -> str:
    if value.startswith("devgroup/"):
        name = value.split("/", 1)[1]
        group = context.configs.require("DevGroup", name)
        config = context.configs.resolve_object(group, DevGroupConfig)
        return f"{direction}group {int(config.id)}"
    if value.startswith("interface/"):
        value = value.split("/", 1)[1]
    return f'{direction}name "{_nft_string(value)}"'


def _service_match(value: str) -> str:
    if "/" not in value:
        raise ValueError(f"service must be protocol/port, got {value!r}")
    proto, port = value.split("/", 1)
    if proto not in {"tcp", "udp"}:
        raise ValueError(f"service protocol must be tcp or udp, got {proto!r}")
    return f"{proto} dport {_port_set(port)}"


def _nat_match(context: UpdateContext, item: dict[str, Any]) -> str:
    parts: list[str] = []
    family = str(item.get("family", "ip"))
    if family == "ip":
        parts.append("meta nfproto ipv4")
    elif family == "ip6":
        parts.append("meta nfproto ipv6")
    for field, nft_field in (("iif", "iifname"), ("oif", "oifname")):
        if item.get(field):
            value = str(item[field])
            if value.startswith("devgroup/"):
                parts.append(_subject_selector(context, value, direction=field))
            else:
                parts.append(f'{nft_field} "{_nft_string(value.removeprefix("interface/"))}"')
    if item.get("saddr"):
        parts.append(f"{family} saddr {item['saddr']}")
    if item.get("daddr"):
        parts.append(f"{family} daddr {item['daddr']}")
    if item.get("daddrNot"):
        parts.append(f"{family} daddr != {item['daddrNot']}")
    return " ".join(parts)


def _render_hairpin(item: dict[str, Any], family: str) -> str:
    hairpin = item["hairpin"]
    proto = str(item["proto"])
    to_port = item.get("toPort", item["dport"])
    match = (
        f"{family} saddr {hairpin['sourceNet']} {family} daddr {item['to']} "
        f"{proto} dport {_port_set(to_port)}"
    )
    if hairpin.get("snat") == "to-address":
        return f"add rule inet {NAT_TABLE} snat_postrouting {match} snat to {hairpin['snatTo']}"
    return (
        f"add rule inet {NAT_TABLE} snat_postrouting {match} "
        f"snat to {family} saddr & 0.255.255.255 | 255.0.0.0"
    )


def _nat_chain(kind: str) -> str:
    if kind in {"portmap", "ipmap", "raw"}:
        return "dnat_prerouting"
    if kind == "snat":
        return "snat_postrouting"
    return "masquerade_postrouting"


def _structured_group_values(context: UpdateContext, values: object) -> list[str]:
    groups: list[str] = []
    for value in _list_values(values):
        name = value.removeprefix("devgroup/")
        group = context.configs.require("DevGroup", name)
        config = context.configs.resolve_object(group, DevGroupConfig)
        groups.append(str(int(config.id)))
    return groups


def _mark_ingress_match(context: UpdateContext, match: dict[str, Any]) -> str:
    parts: list[str] = []
    if match.get("iif"):
        values = _list_values(match["iif"])
        parts.append(_nft_interface_set("iifname", values))
    group_values = match.get("iifGroup", match.get("iif_group"))
    if group_values:
        groups = _structured_group_values(context, group_values)
        if groups:
            parts.append(_nft_set("iifgroup", groups, quote=False))
    return " ".join(parts)


def _mark_set_expr_for_rule(context: UpdateContext, item: dict[str, Any]) -> str:
    if item.get("fwMark"):
        resource = context.configs.require("FwMark", str(item["fwMark"]))
        config = context.configs.resolve_object(resource, FwMarkConfig)
        return _mark_set_expr(config.mark, config.mask)
    return _mark_set_expr(item["mark"], item["mask"])


def _mark_set_expr(mark: object, mask: object) -> str:
    clear_mask = _format_hex32((~_parse_u32(mask)) & 0xFFFFFFFF)
    return f"meta mark set meta mark & {clear_mask} | {_format_mark(mark)}"


def _format_mark(value: object) -> str:
    if isinstance(value, int):
        return _format_hex32(value)
    return str(value)


def _parse_u32(value: object) -> int:
    parsed = int(str(value), 0) if not isinstance(value, int) else value
    if not 0 <= parsed <= 0xFFFFFFFF:
        raise ValueError(f"not a 32-bit value: {value}")
    return parsed


def _format_hex32(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08x}"


def _resolve_raw_devgroups(context: UpdateContext, rule: str) -> str:
    def replace(match: re.Match[str]) -> str:
        keyword = match.group(1)
        value = match.group(2)
        if value.isdigit():
            return match.group(0)
        name = value.removeprefix("devgroup/")
        group = context.configs.require("DevGroup", name)
        config = context.configs.resolve_object(group, DevGroupConfig)
        return f"{keyword} {int(config.id)}"

    return re.sub(
        r"\b(iifgroup|oifgroup)\s+(devgroup/[A-Za-z0-9_.:-]+|[A-Za-z0-9_.:-]+)",
        replace,
        rule,
    )


def _raw_devgroup_references(rule: str) -> list[str]:
    pattern = r"\b(?:iifgroup|oifgroup)\s+(devgroup/[A-Za-z0-9_.:-]+|[A-Za-z0-9_.:-]+)"
    return re.findall(pattern, rule)


def _list_values(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    return [str(value)]


def _nft_interface_set(field: str, values: list[str]) -> str:
    return _nft_set(field, values, quote=True)


def _nft_set(field: str, values: list[str], *, quote: bool) -> str:
    if len(values) == 1:
        value = f'"{_nft_string(values[0])}"' if quote else values[0]
        return f"{field} {value}"
    rendered = [f'"{_nft_string(value)}"' if quote else value for value in values]
    return f"{field} {{ {', '.join(rendered)} }}"


def _port_set(value: object) -> str:
    if isinstance(value, list):
        return "{ " + ", ".join(str(item) for item in value) + " }"
    return str(value)


def _nft_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
