from __future__ import annotations

from pydantic import ValidationError

from dros.config_objects import ConfigObject, ResolvConfConfig
from dros.plugins.base import DrosPlugin, UpdateContext

RESOLV_CONF_PATH = "/etc/resolv.conf"


def create_plugin() -> DrosPlugin:
    return DrosPlugin(
        name="network.resolvconf",
        config_kinds=frozenset({"ResolvConf"}),
        managed_files=frozenset({RESOLV_CONF_PATH}),
        validation_hook=validate,
        update_hook=update,
    )


def validate(context: UpdateContext, objects: list[ConfigObject]) -> list[str]:
    errors: list[str] = []
    for obj in objects:
        if obj.kind != "ResolvConf":
            continue
        if obj.name != "system":
            errors.append(f"ResolvConf/{obj.name}: metadata.name must be system")
        config = _validate_model(context, obj, errors)
        if config is None:
            continue
        if not config.nameservers:
            errors.append(f"ResolvConf/{obj.name}: spec.nameservers must contain at least one item")
        _validate_single_line_items(obj, "nameservers", config.nameservers, errors)
        _validate_single_line_items(obj, "search", config.search, errors)
        _validate_single_line_items(obj, "options", config.options, errors)
    return errors


def update(context: UpdateContext, objects: list[ConfigObject]) -> None:
    for obj in sorted(objects, key=lambda item: item.name):
        config = context.configs.resolve_object(obj, ResolvConfConfig)
        context.executor.write_file(RESOLV_CONF_PATH, _render_resolv_conf(obj, config))


def _validate_model(
    context: UpdateContext,
    obj: ConfigObject,
    errors: list[str],
) -> ResolvConfConfig | None:
    try:
        return context.configs.resolve_object(obj, ResolvConfConfig)
    except ValidationError as exc:
        for error in exc.errors():
            location = ".".join(str(part) for part in error["loc"])
            errors.append(f"ResolvConf/{obj.name}: spec.{location}: {error['msg']}")
        return None


def _validate_single_line_items(
    obj: ConfigObject,
    field_name: str,
    values: list[str],
    errors: list[str],
) -> None:
    for index, value in enumerate(values):
        if "\n" in value or "\r" in value:
            errors.append(f"ResolvConf/{obj.name}: spec.{field_name}[{index}] must be a single line")


def _render_resolv_conf(obj: ConfigObject, config: ResolvConfConfig) -> str:
    lines = [
        "# Generated by DROS. Manual changes will be overwritten.",
        f"# Resource: ResolvConf/{obj.name}",
    ]
    for nameserver in config.nameservers:
        lines.append(f"nameserver {nameserver}")
    if config.search:
        lines.append("search " + " ".join(config.search))
    if config.options:
        lines.append("options " + " ".join(config.options))
    lines.append("")
    return "\n".join(lines)
